export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const GET_LINKS_SUCCESS = "GET_LINKS_SUCCESS";
export const GET_LINKS_FAILURE = "GET_LINKS_FAILURE";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS";
export const EDIT_USER_DATA_FAILURE = "EDIT_USER_DATA_FAILURE";
export const EDIT_USER_DATA_LOCAL = "EDIT_USER_DATA_LOCAL";
export const PRELOADER_CLOSE = "PRELOADER_CLOSE";
export const WISHLIST_REQUEST = "WISHLIST_REQUEST";
export const WISHLIST_GET_SUCCESS = "WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAILURE = "WISHLIST_GET_FAILURE";
export const WISHLIST_ADD_ITEM_SUCCESS = "WISHLIST_ADD_ITEM_SUCCESS";
export const WISHLIST_ADD_ITEM_FAILURE = "WISHLIST_ADD_ITEM_FAILURE";
export const WISHLIST_DELETE_ITEM_SUCCESS = "WISHLIST_DELETE_ITEM_SUCCESS";
export const WISHLIST_DELETE_ITEM_FAILURE = "WISHLIST_DELETE_ITEM_FAILURE";
export const WISHLIST_LOG_OUT = "WISHLIST_LOG_OUT";
export const USER_FROM_JWT = "USER_FROM_JWT";

// ----------- Last-view -----------
export const ADD_TO_LAST_VIEW_SUCCESS = "ADD_TO_LAST_VIEW_SUCCESS";
export const ADD_CURRENT_ID = "ADD_CURRENT_ID";

// ----------- Filters -----------
export const GET_ALL_PRODUCT_LISTING = "GET_ALL_PRODUCT_LISTING";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_LISTING = "GET_PRODUCT_LISTING";
export const GET_CATEGORY_LISTING = "GET_CATEGORY_LISTING";
export const GET_COLOR_LISTING = "GET_COLOR_LISTING";
export const GET_SIZE_LISTING = "GET_SIZE_LISTING";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_COLOR = "SELECT_COLOR";
export const REMOVE_COLOR = "REMOVE_COLOR";
export const SELECT_SIZE = "SELECT_SIZE";
export const REMOVE_SIZE = "REMOVE_SIZE";
export const SELECT_PRICE = "SELECT_PRICE";
export const SELECT_CURRENT_PAGE = "SELECT_CURRENT_PAGE";
export const TOGGLE_COLOR_CHECK = "TOGGLE_COLOR_CHECK";
export const TOGGLE_SIZES_CHECK = "TOGGLE_COLOR_CHECK";

// ----------- CART -----------
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";
export const ACTUALIZATION_LOCAL_CART_SUCCESS =
  "ACTUALIZATION_LOCAL_CART_SUCCESS";
export const ACTUALIZATION_LOCAL_CART_FAILURE =
  "ACTUALIZATION_LOCAL_CART_FAILURE";
export const ADD_ITEM_CART_LOCAL_SUCCESS = "ADD_ITEM_CART_LOCAL_SUCCESS";
export const ADD_ITEM_CART_LOCAL_FAILURE = "ADD_ITEM_CART_LOCAL_FAILURE";
export const ADD_ITEM_CART_SUCCESS = "ADD_ITEM_CART_SUCCESS";
export const ADD_ITEM_CART_FAILURE = "ADD_ITEM_CART_FAILURE";
export const DECREASE_ITEM_CART_LOCAL = "DECREASE_ITEM_CART_LOCAL";
export const DECREASE_ITEM_CART_SUCCESS = "DECREASE_ITEM_CART_SUCCESS";
export const DECREASE_ITEM_CART_FAILURE = "DECREASE_ITEM_CART_FAILURE";
export const DELETE_ITEM_CART_LOCAL = "DELETE_ITEM_CART_LOCAL";
export const DELETE_ITEM_CART_SUCCESS = "DELETE_ITEM_CART_SUCCESS";
export const DELETE_ITEM_CART_FAILURE = "DELETE_ITEM_CART_FAILURE";
export const CHANGE_ITEM_CART_QUANTITY_LOCAL =
  "CHANGE_ITEM_CART_QUANTITY_LOCAL";
export const CHANGE_ITEM_CART_QUANTITY_SUCCESS =
  "CHANGE_ITEM_CART_QUANTITY_SUCCESS";
export const CHANGE_ITEM_CART_QUANTITY_FAILURE =
  "CHANGE_ITEM_CART_QUANTITY_FAILURE";
export const CLEAR_CART = "CLEAR_CART";
